### ISSUE TITLE
invalid syntax SwissArmyTransformer

### ISSUE THREAD

**Issue by AK391** [THUDM/CogView2#4]
getting this error when running

text2image.sh --input-source input.txt

Traceback (most recent call last):
  File "cogview2_text2image.py", line 20, in <module>
    from SwissArmyTransformer.model import CachedAutoregressiveModel
  File "/usr/local/lib/python3.7/dist-packages/SwissArmyTransformer/model/__init__.py", line 5, in <module>
    from .encoder_decoder_model import EncoderDecoderModel
  File "/usr/local/lib/python3.7/dist-packages/SwissArmyTransformer/model/encoder_decoder_model.py", line 85
    return encoder_outputs, decoder_outputs, *mems
                                             ^
SyntaxError: invalid syntax

using SwissArmyTransformer==0.2.1

**Comment by jhurlbut** [comment]
upgrade to python 3.8?
