### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/sharefs'

### ISSUE THREAD

**Issue by BestTao** [THUDM/CogView2#41]
(py3.8) 202312150037@ubuntu:/data/zht/learn_pytorch/CogView2-main$ ./text2image.sh --input-source input.txt
[2024-04-03 09:01:21,408] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Please install apex to use fused_layer_norm, fall back to torch.nn.LayerNorm
WARNING: No training data specified
using world size: 1 and model-parallel size: 1 
> initializing model parallel with size 1
Traceback (most recent call last):
  File "cogview2_text2image.py", line 233, in <module>
    main(args)
  File "cogview2_text2image.py", line 48, in main
    model, args = InferenceModel.from_pretrained(args, 'coglm')
  File "/home/202312150037/anaconda3/envs/py3.8/lib/python3.8/site-packages/SwissArmyTransformer/model/base_model.py", line 152, in from_pretrained
    model_path = auto_create(name, path=home_path, url=url)
  File "/home/202312150037/anaconda3/envs/py3.8/lib/python3.8/site-packages/SwissArmyTransformer/resources/download.py", line 36, in auto_create
    os.makedirs(os.path.dirname(file_path), exist_ok=True)
  File "/home/202312150037/anaconda3/envs/py3.8/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/202312150037/anaconda3/envs/py3.8/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/sharefs'

**Comment by BestTao** [comment]
问题已解决，/home/202312150037/anaconda3/envs/py3.8/lib/python3.8/site-packages/SwissArmyTransformer/model/base_model.py在这个文件的152行，将原来的model_path = auto_create(name, path=home_path, url=url)，更改为model_path = auto_create('coglm', path='/data/zht/learn_pytorch/CogView2-main/save_models')，路径设置为自己的模型路径即可

**Comment by BestTao** [comment]
已解决，更改路径即可
